In [4]:
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import normalize
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn import svm
from pandas import read_csv
from pandas import DataFrame
from pandas import concat
import numpy as np
import re


def xy_sets(line):
    X=None
    y=None
    indexes = map(int, re.findall('\d+', line))
    aux = False
    for i in indexes:
        if aux is False:
            X = scaled[i, :]
            y = target[i]
            aux = True
            continue
        X = np.vstack((X, scaled[i, :]))
        y = np.hstack((y, target[i]))
        
    return X, y, indexes


multiplier = ['0,01', '0,001']
dataset_name = ['57EDG', '54BND', 'combined']
m = '0,001'
k = 3
name = '57EDG'

# load dataset
dataset = read_csv(name+'_'+m+'.csv', header=0, index_col=(0,1))
values = dataset.values

# split data set into data(input) and target(output)
data = values[:, 1:] 
target = values[:, 0]

# normalize features
scaled = normalize(data[:, :3], norm='max', axis=0)
scaled = np.concatenate((scaled, data[:, :4]), axis = 1)

scores = np.zeros(20)

cont = 0
file = open(name+'_kf.txt', 'r')
while cont < 20:
    
    train_line = file.readline()
    test_line = file.readline()
    
    X_train, y_train, train_indexes = xy_sets(train_line)
    X_test, y_test, test_indexes = xy_sets(test_line)
    
    classifier = KNeighborsClassifier(n_neighbors=k)  # classifier 
    classifier.fit(X_train, y_train)
                
    y_pred = classifier.predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))  

    cont += 1
    
file.close()

print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[[1 0]
 [0 2]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         1
         1.0       1.00      1.00      1.00         2

   micro avg       1.00      1.00      1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

[[2 0]
 [1 0]]
              precision    recall  f1-score   support

         0.0       0.67      1.00      0.80         2
         1.0       0.00      0.00      0.00         1

   micro avg       0.67      0.67      0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3

[[1 0]
 [0 2]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         1
         1.0       1.00      1.00      1.00         2

   micro avg       1.00      1.00      1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      

C:\Users\rodri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rodri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rodri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
